server:
  port: '8081'
spring:
  h2:
    console:
      enabled: true
      path: /h2Test
      settings:
        web-allow-others: true
  datasource:
    url: 'jdbc:h2:~/test2test;'
    driverClassName: org.h2.Driver
    username: sa
  jpa:
    defer-datasource-initialization: true
    hibernate:
      ddl-auto: validate
    database-platform: org.hibernate.dialect.H2Dialect
    properties:
      hibernate:
        dialect: org.hibernate.dialect.H2Dialect
        show_sql: true
  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher


  sql:
    init:
      mode: always

timeZone:
  location:
    asia_seoul: "Asia/Seoul"

multipart:
  upload:
    path: "/upload/"

jwt:
  token:
    secret-key: "cos_jwt_token_test"
