CREATE ALIAS IF NOT EXISTS FT_INIT FOR "org.h2.fulltext.FullText.init";
CALL FT_INIT();
CALL FT_DROP_INDEX('PUBLIC', 'RENT_POST');
CALL FT_CREATE_INDEX('PUBLIC', 'RENT_POST', 'RENT_POST_NAME');

INSERT INTO CATEGORY(NAME) VALUES('인기리스트');

INSERT INTO CATEGORY(NAME) VALUES('수입명품');

INSERT INTO CATEGORY(NAME) VALUES('캠핑용품');

INSERT INTO CATEGORY(NAME) VALUES('카메라/캠코더');

INSERT INTO CATEGORY(NAME) VALUES('음향/음반');

INSERT INTO CATEGORY(NAME) VALUES('리빙/생활');

INSERT INTO CATEGORY(NAME) VALUES('레져/여행');

INSERT INTO CATEGORY(NAME) VALUES('유아동');

INSERT INTO CATEGORY(NAME) VALUES('뷰티');

INSERT INTO CATEGORY(NAME) VALUES('게임');

INSERT INTO CATEGORY(NAME) VALUES('도서/문구');

INSERT INTO CATEGORY(NAME) VALUES('반려동물');


INSERT INTO LOCATION(NAME) VALUES('서울');
INSERT INTO LOCATION(NAME) VALUES('인천');
INSERT INTO LOCATION(NAME) VALUES('경기');
INSERT INTO LOCATION(NAME) VALUES('강원');
INSERT INTO LOCATION(NAME) VALUES('대전');
INSERT INTO LOCATION(NAME) VALUES('세종');
INSERT INTO LOCATION(NAME) VALUES('전북');
INSERT INTO LOCATION(NAME) VALUES('전남');
INSERT INTO LOCATION(NAME) VALUES('부산');
INSERT INTO LOCATION(NAME) VALUES('경북');
INSERT INTO LOCATION(NAME) VALUES('경남');
INSERT INTO LOCATION(NAME) VALUES('제주');

